// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2K0Yu78TZaEdguzb7pJ63FxpdAMuajcw',
    appId: '1:510818677442:web:4c3a10d7fced681cb2015b',
    messagingSenderId: '510818677442',
    projectId: 'studyapp-dfe0e',
    authDomain: 'studyapp-dfe0e.firebaseapp.com',
    storageBucket: 'studyapp-dfe0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6BbEwX_ptmO6zS0G4YHCt1szz5PYUUo',
    appId: '1:510818677442:android:35b8b7da5e2823a0b2015b',
    messagingSenderId: '510818677442',
    projectId: 'studyapp-dfe0e',
    databaseURL: 'https://studyapp-dfe0e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studyapp-dfe0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdMEGr_4CoXv8O2YxoYMKBIrO6pvw3oP4',
    appId: '1:510818677442:ios:3651e63c03e4f167b2015b',
    messagingSenderId: '510818677442',
    projectId: 'studyapp-dfe0e',
    databaseURL: 'https://studyapp-dfe0e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studyapp-dfe0e.firebasestorage.app',
    iosBundleId: 'com.example.studyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdMEGr_4CoXv8O2YxoYMKBIrO6pvw3oP4',
    appId: '1:510818677442:ios:04bdbb8654dac87db2015b',
    messagingSenderId: '510818677442',
    projectId: 'studyapp-dfe0e',
    storageBucket: 'studyapp-dfe0e.firebasestorage.app',
    iosBundleId: 'com.example.study',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2K0Yu78TZaEdguzb7pJ63FxpdAMuajcw',
    appId: '1:510818677442:web:770993bd768c42a5b2015b',
    messagingSenderId: '510818677442',
    projectId: 'studyapp-dfe0e',
    authDomain: 'studyapp-dfe0e.firebaseapp.com',
    storageBucket: 'studyapp-dfe0e.firebasestorage.app',
  );
}